#!/bin/sh
#
# Script to do DNS lookups
#
set -euf ; (set -o pipefail 2>/dev/null) && set -o pipefail

if [ $# -eq 0 ] ; then
  cat <<-EOF
	Usage:
	  $0 dns_name [default]
	EOF
  exit
fi

read_entry() {
  local dns_name="$1" ; shift
  if [ $# -gt 0 ] ; then
    default="$1"
    shift
  else
    default="0.0.0.0"
  fi
  local ips
  if ips=$(getent hosts "$dns_name" | awk '{print $1}') ; then
    if [ -n "$ips" ]  ; then
      echo $ips
      return 0
    fi
  fi
  echo "$default"
}


raw=$(read_entry "$@")
jq -M -n --arg my_output "$raw" '{"value": $my_output}'
